backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  branch: main
  squash_merges: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "knowledge_hub"
    label: "Knowledge Hub"
    folder: "content/knowledge-hub"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Read More URL", name: "url", widget: "string" }
